/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba1_programacionii;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class BuscarItem extends javax.swing.JFrame {

    /**
     * Creates new form BuscarItem
     */
    public BuscarItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MostrarField = new javax.swing.JTextField();
        CodigoField = new javax.swing.JTextField();
        TipoItemBox = new javax.swing.JComboBox<>();
        BotonRegresar = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MostrarField.setEditable(false);
        MostrarField.setBackground(new java.awt.Color(255, 255, 255));
        MostrarField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        MostrarField.setForeground(new java.awt.Color(159, 77, 79));
        MostrarField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MostrarField.setBorder(null);
        jPanel1.add(MostrarField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 407, 600, 40));

        CodigoField.setBackground(new java.awt.Color(255, 255, 255));
        CodigoField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CodigoField.setForeground(new java.awt.Color(159, 77, 79));
        CodigoField.setBorder(null);
        CodigoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoFieldKeyTyped(evt);
            }
        });
        jPanel1.add(CodigoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 233, 270, 40));

        TipoItemBox.setBackground(new java.awt.Color(255, 255, 255));
        TipoItemBox.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TipoItemBox.setForeground(new java.awt.Color(159, 77, 79));
        TipoItemBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Movie", "Game" }));
        TipoItemBox.setBorder(null);
        TipoItemBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TipoItemBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 233, 190, 40));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 50, 40));

        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/BuscarItem.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseClicked
        int codigo = -1;
        codigo = Integer.parseInt(CodigoField.getText());
        String tipoItem = (String) TipoItemBox.getSelectedItem();
        
        if (codigo == -1) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Código.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (tipoItem.equals(" ")) {
            JOptionPane.showMessageDialog(null, "Elije un Tipo de Item.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        BlockBusterItem mensaje = Main_BlockBuster.blockBuster.buscarItem(codigo, tipoItem);
        
        if (mensaje != null) {
            MostrarField.setText(mensaje.toString());
        } else {
            JOptionPane.showMessageDialog(null, "El código ingresado no existe en el sistema.", "Error: Código Inexistente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonBuscarMouseClicked

    private void CodigoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoFieldKeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            evt.consume();
        }
    }//GEN-LAST:event_CodigoFieldKeyTyped

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonBuscar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JTextField CodigoField;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField MostrarField;
    private javax.swing.JComboBox<String> TipoItemBox;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
