/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba1_programacionii;

/**
 *
 * @author jenniferbueso
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregarItem = new javax.swing.JLabel();
        BotonAuditarEstado = new javax.swing.JLabel();
        BotonBuscarItem = new javax.swing.JLabel();
        BotonRentar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarItemMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 180, 130));

        BotonAuditarEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAuditarEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAuditarEstadoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAuditarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 180, 130));

        BotonBuscarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarItemMouseClicked(evt);
            }
        });
        jPanel1.add(BotonBuscarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 180, 130));

        BotonRentar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRentar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRentarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, 130));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/MenuPrincipal.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarItemMouseClicked
        BuscarItem buscarItem = new BuscarItem();
        buscarItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonBuscarItemMouseClicked

    private void BotonAgregarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarItemMouseClicked
        AgregarItem agregarItem = new AgregarItem();
        agregarItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarItemMouseClicked

    private void BotonRentarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRentarMouseClicked
        RentarItem rentarItem = new RentarItem();
        rentarItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRentarMouseClicked

    private void BotonAuditarEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAuditarEstadoMouseClicked
        AuditarMovies auditarMovies = new AuditarMovies();
        auditarMovies.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAuditarEstadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregarItem;
    private javax.swing.JLabel BotonAuditarEstado;
    private javax.swing.JLabel BotonBuscarItem;
    private javax.swing.JLabel BotonRentar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
